---
database:
  host: localhost
  name: "{{ site.username }}_db"
  sub_name: "{{ site.subdomain | default('subdomain') }}_db"
  username: "{{ site.username }}_user"
  password: "{{ lookup('password', playbook_dir + '/credentials/' + site.domain + '/database.txt chars=ascii_letters,digits length=20') }}"
  type: mysql
