---
- name: Creating site directory
  file: path={{ site_directory }}/site
        state=directory
        mode=0775

- name: Creating cache directory
  file: path={{ site_directory }}/site/cache
        state=directory
        mode=0775

- name: Clear cache directory
  command: rm -f *
  args:
    chdir: "{{ site_directory }}/site/cache"

- name: Uploading site data
  copy: src={{ local_site_directory }}/data
        dest={{ site_directory }}/site

- name: Uploading site scripts
  copy: src={{ local_site_directory }}/scripts
        dest={{ site_directory }}/site

- name: Uploading site styles
  copy: src={{ local_site_directory }}/styles
        dest={{ site_directory }}/site

- name: Uploading site templates
  copy: src={{ local_site_directory }}/templates
        dest={{ site_directory }}/site

- name: Uploading site images
  copy: src={{ local_site_directory }}/images
        dest={{ site_directory }}/site

- name: Uploading site configuration file
  copy: src={{ local_site_directory }}/config.php
        dest={{ site_directory }}/site/config.php

- name: Configuring backend password
  lineinfile: dest={{ site_directory }}/site/data/system_init.xml
              regexp="^\s*password=\"\""
              line="		password=\"{{ backend_password }}\""

- name: Configuring time zone
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^define\('_TIMEZONE', '.*'\);"
              line="define('_TIMEZONE', '{{ timezone }}');"

- name: Configuring database host
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^\s+'host'\s=>\s'.*',"
              line="		'host' => '{{ database.host }}',"

- name: Configuring database username
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^\s+'user'\s=>\s'.*',"
              line="		'user' => '{{ database.username }}',"

- name: Configuring database password
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^\s+'pass'\s=>\s'.*',"
              line="		'pass' => '{{ database.password }}',"

- name: Configuring database name for domain
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^\s+'name'\s=>\s'.*'"
              line="		'name' => '{{ database.name }}'"
  when: site.subdomain is not defined

- name: Configuring database name for subdomain
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^\s+'name'\s=>\s'.*'"
              line="		'name' => '{{ database.sub_name }}'"
  when: site.subdomain is defined
